name: Build and Publish to PyPI/TestPyPI

on:
  push:
    tags:
      - 'v*'  # Triggers only when you push a tag like v0.0.2 or v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml

    - name: Build the package
      run: python -m build

    - name: Upload to TestPyPI
      if: startsWith(github.ref_name, 'v0.')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPYPI }}
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*

    - name: Upload to PyPI
      if: startsWith(github.ref_name, 'v1.') || startsWith(github.ref_name, 'v2.')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI }}
      run: |
        twine upload dist/*
